language: java
jdk:
  - oraclejdk8
before_install:
  openssl aes-256-cbc -K $encrypted_3fc90a153911_key -iv $encrypted_3fc90a153911_iv -in travis/secring.gpg.enc -out travis/secring.gpg -d
install: true
script:
  - ./gradlew -x test uploadArchives -PossrhUsername=zakgof -PossrhPassword=${OSSRH_PASSWORD} -Psigning.keyId=${SIGNING_KEY_ID} -Psigning.password=${SIGNING_PASSWORD} -Psigning.secretKeyRingFile=travis/secring.gpg
