language: java
jdk:
  - oraclejdk8
script: mvn deploy --altDeploymentRepository diet::default::http://nexus2-zakk.rhcloud.com/content/repositories/snapshots/ --settings travis/settings.xml -DskipTests -B