language: java
jdk:
  - oraclejdk8
install:
after_success:
  - mvn deploy --altDeploymentRepository diet::default::http://nexus2-zakk.rhcloud.com/nexus/content/repositories/snapshots/ --settings travis/settings.xml -DskipTests -B