language: java
jdk:
  - oraclejdk8
install:
script: mvn -DaltDeploymentRepository=velvetdb::default::http://nexus2-zakk.rhcloud.com/content/repositories/snapshots/ -B -Dmaven.test.skip=true -DskipTests -s "travis/settings.xml" deploy