version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew test publish -PossrhUsername=zakgof -PossrhPassword=${OSSRH_PASSWORD}
