package com.zakgof.db.velvet.entity;

/**
 * Keyless entity definition - specifies a kind of entities with values represented by class V. Long keys are not stored in entities, they are generated by database when adding entities.
 *
 * @param <V> value type
 */
public interface IKeylessEntityDef<V> extends ISortableEntityDef<Long, V> {
}
